<a href="https://colab.research.google.com/github/juel-123/Online_Retail_Customer_Segmentation/blob/main/Online_Retail_Customer_Segmentation_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#*Project Title : Online Retail Customer Segmentation*

Project type :Unsupervised ML

Contribution: Indiviual

#*Github link:*

#*Project Summary*

The aim of this ML project is to perform segmentation for an online retail business. Customer segmentation involves dividing a cusdtomer base into distinct groups on shared characteristics, behaviours,or preferences.By effectively segmenting customers, businesses can gain valuable insights and tailor their marketing strategies to specific customer Groups, leading to improved customer satisfaction and increased profitability.

Dataset : The project utilizes a dataset containing relevant information about the online retail customers. The dataset contains features such as Customer Demographics, Purchase history, frequency of purchases, monetary value of purchases, and other relevant variables that can help segmenting customers effectively.

Primary objective: The primary objective of this is to apply ML techniques to segment the online retail customers in to meaningful groups based on their purchasing behaviour and characteristics. This segmentation will help the business to better understanding it's customer base, identifying the pattern, trends and develop personalized marketing campaigns to target each segment.

#*Problem statement*

In this Project, our task is to major customer segments on a transcational data set which contains all the transcations occuring between 01/12/2010 and 09//12/2011 for a UK-based and register the non-store online retail.The company mainly sells unique all-ocassional gifts. Many customers of the company are the wholesalers.

#*Data Description*

Attribute information:



* Invoice : Invoce no ,Nominal , a 6-digit integral number assigned to each transcation. if this code starts with 'c' indicates a cancellation.

* StockCode : Product(item) code.Nominal , a 5-digit integral number uniquely assigned to each distinct product.  
*  Description: Product (item) name.Nominal


*  Quantity : The quantities of each product per transcation. Numeric.


* InvoiceDate : Invoice date and time. Numeric, the day and time when each transcation was generated.  
*  Unit price: Unit price, Product price on unit selling.

#*Importing libararies*

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#*Importing dataset*

In [3]:
# importing dataset
df = pd.read_csv('/content/drive/MyDrive/Online Retail.xlsx - Online Retail.csv')

In [4]:
# First five rows of the dataset
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom

In [5]:
# last five rows of the dataset
df.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/11 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/11 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/11 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/11 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/11 12:50,4.95,12680.0,France

In [6]:
# shape of the dataset
df.shape

(541909, 8)

There are 541909 rows and 8 columns

In [7]:
# statistial analysis
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [76]:
# Information of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   541909 non-null  object
 7   Country      541909 non-null  object
 8   Amount       541909 non-null  float64
 9   diff         541909 non-null  timedelta64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(5), timedelta64[ns](1)
memory usage: 41.3+ MB

#*Data Cleaning*

In [9]:
# checking null values
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

We an see Description and CustomerID has some null values and we need to fix it.

In [10]:
# dropping rows with mising values
df.dropna()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/11 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/11 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/11 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/11 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/11 12:50,4.95,12680.0,France

Now we are having 406829 rows and 8 columns.

In [11]:
# changing the datatype of customerId
df['CustomerID']= df['CustomerID'].astype(str)

In [49]:
#Adding new feature: Monetary
df['Amount'] = df['UnitPrice']*df['Quantity']
rfm_m =pd.DataFrame( df.groupby('CustomerID')['Amount'].sum())
rfm_m = rfm_m.reset_index()
rfm_m.head()

  CustomerID   Amount
0    12346.0     0.00
1    12347.0  4310.00
2    12348.0  1797.24
3    12349.0  1757.55
4    12350.0   334.40

In [50]:
# new feature: Frequency
rfm_f = pd.DataFrame(df.groupby('CustomerID')['InvoiceNo'].count())
rfm_f = rfm_f.reset_index()
rfm_f.columns= ['CustomerID','Frequecy']
rfm_f.head()

  CustomerID  Frequecy
0    12346.0         2
1    12347.0       182
2    12348.0        31
3    12349.0        73
4    12350.0        17

In [51]:
# merging two dfs
rfm = pd.merge(rfm_m,rfm_f, on = 'CustomerID', how='inner')
rfm.head()

  CustomerID   Amount  Frequecy
0    12346.0     0.00         2
1    12347.0  4310.00       182
2    12348.0  1797.24        31
3    12349.0  1757.55        73
4    12350.0   334.40        17

In [29]:
# new feature : Recency
# convert datetime to proper datetime
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], format='%d/%m/%y %H:%M')

In [30]:
# compute the maximun date to know the last transcation date
max_date = max(df['InvoiceDate'])
max_date

Timestamp('2011-12-09 12:50:00')

In [31]:
# compute the difference between the max date and transcation date
df['diff'] = max_date - df['InvoiceDate']
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Amount,diff
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,373 days 04:24:00
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,373 days 04:24:00
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,373 days 04:24:00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,373 days 04:24:00
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,373 days 04:24:00

In [65]:
# Compute the Recency
rfm_r = pd.DataFrame(df.groupby('CustomerID')['diff'].min())
rfm_r = rfm_r.reset_index()
rfm_r.head()

  CustomerID              diff
0    12346.0 325 days 02:33:00
1    12347.0   1 days 20:58:00
2    12348.0  74 days 23:37:00
3    12349.0  18 days 02:59:00
4    12350.0 309 days 20:49:00

In [84]:
rfm_r.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4373 entries, 0 to 4372
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CustomerID  4373 non-null   object
 1   diff        4373 non-null   datetime64[ns]
dtypes: datetime64[ns](1), object(1)
memory usage: 68.5+ KB

In [83]:
rfm_r = rfm_r.drop(columns=['rfm_r'])

In [98]:
rfm = rfm.drop(columns=['diff_x','diff_y'])

In [99]:
# merging the dataframe to get final RFM dataframe
rfm = pd.merge(rfm,rfm_r,on= 'CustomerID',how='inner')
rfm.head()

  CustomerID   Amount  Frequecy                          diff
0    12346.0     0.00         2 1970-01-01 00:00:00.000000325
1    12347.0  4310.00       182 1970-01-01 00:00:00.000000001
2    12348.0  1797.24        31 1970-01-01 00:00:00.000000074
3    12349.0  1757.55        73 1970-01-01 00:00:00.000000018
4    12350.0   334.40        17 1970-01-01 00:00:00.000000309